const $=id=>document.getElementById(id);
const DB='mystery-book-studio-v12';
let current=null,dragId=null;
let state={title:"Pete's Mystery Colouring Book",cover:null,insideText:"Made especially for Pete\n\nFor all the evenings we spend colouring together.",insideImage:null,designs:[],galleryPages:[]};
function db(){return new Promise((r,j)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains('p'))q.result.createObjectStore('p')};q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)})}
async function save(){const d=await db();await new Promise((r,j)=>{const t=d.transaction('p','readwrite');t.objectStore('p').put(state,'main');t.oncomplete=r;t.onerror=()=>j(t.error)});$('saveState').textContent='Saved ✓';renderAll()}
async function load(){try{const d=await db();const v=await new Promise((r,j)=>{const t=d.transaction('p');const q=t.objectStore('p').get('main');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});if(v)state={...state,...v}}catch(e){};state.designs=(state.designs||[]).map((d,i)=>({...d,number:i+1,pageMode:d.pageMode||'single',orientation:d.orientation||'portrait',swatchCount:d.swatchCount||18,codes:d.codes||null,swatchLeft:d.swatchLeft??5,swatchRight:d.swatchRight??95}));state.galleryPages=state.galleryPages||[];$('bookTitle').value=state.title;$('insideText').value=state.insideText||'';renderAll()}
function fileData(f){return new Promise(r=>{const q=new FileReader();q.onload=()=>r(q.result);q.readAsDataURL(f)})}
function img(src){return new Promise((r,j)=>{const i=new Image();i.onload=()=>r(i);i.onerror=j;i.src=src})}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function hex(c){return'#'+c.map(v=>Math.max(0,Math.min(255,Math.round(v))).toString(16).padStart(2,'0')).join('').toUpperCase()}
function switchView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.v===id));if(id==='bookView')renderBook();scrollTo(0,0)}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchView(b.dataset.v));
$('saveBtn').onclick=save;$('bookTitle').oninput=()=>state.title=$('bookTitle').value;$('insideText').oninput=()=>{state.insideText=$('insideText').value;renderBook()};$('backBtn').onclick=()=>switchView('designsView');
$('coverUpload').onchange=async e=>{if(e.target.files?.[0]){state.cover=await fileData(e.target.files[0]);await save()}};$('removeCover').onclick=async()=>{state.cover=null;$('coverUpload').value='';await save()};
$('insideUpload').onchange=async e=>{if(e.target.files?.[0]){state.insideImage=await fileData(e.target.files[0]);await save()}};$('removeInside').onclick=async()=>{state.insideImage=null;$('insideUpload').value='';await save()};
$('newDesign').onclick=async()=>{current={id:Date.now(),number:state.designs.length+1,name:`Design ${state.designs.length+1}`,pageMode:'single',orientation:'portrait',main:null,line:null,swatchSource:null,artwork:null,mysteryArt:null,palette:null,codes:null,swatchCount:18,swatchLeft:5,swatchRight:95,pairApproved:false,paletteApproved:false,pagesApproved:false,complete:false};state.designs.push(current);await save();openCurrent()};
function status(d){return d.complete?'Complete':d.pagesApproved?'Pages approved':d.paletteApproved?'Swatch page approved':d.pairApproved?'Images approved':'Draft'}
function renderList(){const el=$('designList'),done=state.designs.filter(d=>d.complete).length;$('progress').textContent=`${done} of ${state.designs.length||40} complete`;if(!state.designs.length){el.innerHTML='<div class="note">No designs yet.</div>';return}el.innerHTML=state.designs.map(d=>`<div class="design"><div class="thumb">${d.artwork?`<img src="${d.artwork}">`:''}</div><div><strong>#${d.number} ${esc(d.name)}</strong><br><span class="badge ${d.complete?'ok':''}">${status(d)}</span> <span class="badge">${d.pageMode==='spread'?'2-page spread':d.orientation==='landscape'?'Landscape page':'Portrait page'}</span><div class="miniBtns"><button data-open="${d.id}">Open</button><button class="danger" data-del="${d.id}">Remove</button></div></div></div>`).join('');el.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{current=state.designs.find(d=>d.id==b.dataset.open);openCurrent()});el.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(!confirm('Remove this design?'))return;state.designs=state.designs.filter(d=>d.id!=b.dataset.del);state.designs.forEach((d,i)=>d.number=i+1);state.galleryPages=state.galleryPages.map(p=>p.map(x=>x==b.dataset.del?null:x));await save()})}
function setStage(s){['upload','palette','pages','complete'].forEach(k=>{$(k+'Stage').classList.toggle('hidden',k!==s);const b=document.querySelector(`.stage[data-s="${k}"]`);b.classList.toggle('active',k===s);b.classList.toggle('done',k==='upload'?current?.pairApproved:k==='palette'?current?.paletteApproved:k==='pages'?current?.pagesApproved:current?.complete)});if(s==='palette')renderPalette();if(s==='pages')renderPages();if(s==='complete')renderComplete()}
function setMode(mode){if(!current)return;current.pageMode=mode;if(mode==='spread')current.orientation='landscape';renderModeButtons();renderPages();save()}
function setOrientation(o){if(!current||current.pageMode==='spread')return;current.orientation=o;renderModeButtons();renderPages();save()}
$('singleBtn').onclick=()=>setMode('single');$('spreadBtn').onclick=()=>setMode('spread');$('portraitBtn').onclick=()=>setOrientation('portrait');$('landscapeBtn').onclick=()=>setOrientation('landscape');
function renderModeButtons(){if(!current)return;$('singleBtn').classList.toggle('selected',current.pageMode!=='spread');$('spreadBtn').classList.toggle('selected',current.pageMode==='spread');$('portraitBtn').classList.toggle('selected',current.orientation!=='landscape'&&current.pageMode!=='spread');$('landscapeBtn').classList.toggle('selected',current.orientation==='landscape'&&current.pageMode!=='spread');$('orientationRow').classList.toggle('muted',current.pageMode==='spread')}
async function openCurrent(){if(!current)return;$('editTitle').textContent=`Design #${current.number}`;$('mainPreview').src=current.main||'';$('linePreview').src=current.line||'';$('swatchPreview').src=current.swatchSource||'';$('swatchCount').value=current.swatchCount||18;$('swatchCountVal').textContent=$('swatchCount').value;$('swatchLeft').value=current.swatchLeft??5;$('swatchRight').value=current.swatchRight??95;renderModeButtons();setStage(current.complete?'complete':current.pagesApproved?'complete':current.paletteApproved?'pages':current.pairApproved?'palette':'upload');switchView('editorView')}
$('mainUpload').onchange=async e=>{if(current&&e.target.files?.[0]){current.main=await fileData(e.target.files[0]);$('mainPreview').src=current.main;checkUploads()}};$('lineUpload').onchange=async e=>{if(current&&e.target.files?.[0]){current.line=await fileData(e.target.files[0]);$('linePreview').src=current.line;checkUploads()}};$('swatchUpload').onchange=async e=>{if(current&&e.target.files?.[0]){current.swatchSource=await fileData(e.target.files[0]);$('swatchPreview').src=current.swatchSource;checkUploads()}};
function checkUploads(){$('approvePair').disabled=!(current?.main&&current?.line&&current?.swatchSource)}
$('approvePair').onclick=async()=>{if(!current?.main||!current?.line||!current?.swatchSource)return;current.artwork=current.main;current.mysteryArt=current.line;current.pairApproved=true;current.paletteApproved=false;current.pagesApproved=false;current.complete=false;current.palette=null;current.codes=null;await save();setStage('palette')};
$('swatchCount').oninput=()=>{$('swatchCountVal').textContent=$('swatchCount').value;if(current)current.swatchCount=+$('swatchCount').value};$('swatchLeft').oninput=()=>{if(current)current.swatchLeft=+$('swatchLeft').value};$('swatchRight').oninput=()=>{if(current)current.swatchRight=+$('swatchRight').value};
function defaultCodes(n){const base=['','2','3','4','5','6','7','8','9','0','a','b','c','d','e','f','g','h'];return Array.from({length:n},(_,i)=>base[i]??String(i+1))}
async function readSwatches(){if(!current?.swatchSource)return;const im=await img(current.swatchSource),n=+($('swatchCount').value||18),l=(current.swatchLeft??5)/100,r=(current.swatchRight??95)/100;const x0=im.naturalWidth*l,x1=im.naturalWidth*r,slot=(x1-x0)/n,c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(im,0,0);const colors=[];for(let i=0;i<n;i++){const cx=x0+slot*(i+.5),cy=im.naturalHeight*.5,rx=Math.max(2,slot*.16),ry=Math.max(2,im.naturalHeight*.08);const sx=Math.max(0,Math.floor(cx-rx)),sy=Math.max(0,Math.floor(cy-ry)),sw=Math.max(1,Math.floor(rx*2)),sh=Math.max(1,Math.floor(ry*2));const d=g.getImageData(sx,sy,sw,sh).data;let R=0,G=0,B=0,k=0;for(let p=0;p<d.length;p+=4){const rr=d[p],gg=d[p+1],bb=d[p+2];if(rr>250&&gg>250&&bb>250)continue;R+=rr;G+=gg;B+=bb;k++}colors.push(k?[R/k,G/k,B/k]:[245,240,230])}current.palette=colors;current.codes=current.codes?.length===n?current.codes:defaultCodes(n);renderPalette();await save()}
$('readPalette').onclick=readSwatches;
function keyHTMLFor(d){if(!d?.palette?.length)return'';const codes=d.codes||defaultCodes(d.palette.length);return `<div class="keyTitle">COLOUR KEY</div><div class="keySub">Design ${d.number}</div><div class="keyList">${d.palette.map((c,i)=>`<div class="keyRow"><span class="code">${esc(codes[i]||'')}</span><span class="swatchBlock" style="background:${hex(c)}"></span><span class="writeLine"></span></div>`).join('')}</div>`}
function renderPalette(){if(!current?.palette?.length){$('paletteEditor').innerHTML='<div class="note">Upload the base swatch page, set the swatch count and boundaries, then press <strong>Read swatches</strong>.</div>';$('keyPage').innerHTML='';$('approvePalette').disabled=true;return}const codes=current.codes||defaultCodes(current.palette.length);$('paletteEditor').innerHTML=current.palette.map((c,i)=>`<div class="swatchEdit"><span class="swatchBlock big" style="background:${hex(c)}"></span><input data-code="${i}" value="${esc(codes[i])}" aria-label="Code ${i+1}"><span>${hex(c)}</span></div>`).join('');$('paletteEditor').querySelectorAll('[data-code]').forEach(inp=>inp.oninput=()=>{current.codes[+inp.dataset.code]=inp.value;$('keyPage').innerHTML=keyHTMLFor(current)});$('keyPage').innerHTML=keyHTMLFor(current);$('approvePalette').disabled=false}
$('approvePalette').onclick=async()=>{if(!current?.palette?.length)return;current.paletteApproved=true;await save();setStage('pages')};
function renderPages(){if(!current)return;$('leftPage').innerHTML=keyHTMLFor(current);$('rightPageImg').src=current.mysteryArt||current.line||'';$('mysteryPage').classList.toggle('landscape',current.orientation==='landscape'&&current.pageMode!=='spread');$('spreadPreview').classList.toggle('hidden',current.pageMode!=='spread');$('singlePreview').classList.toggle('hidden',current.pageMode==='spread');if(current.pageMode==='spread'){$('spreadLeftImg').src=current.mysteryArt||current.line||'';$('spreadRightImg').src=current.mysteryArt||current.line||''}}
$('approvePages').onclick=async()=>{current.pagesApproved=true;current.complete=true;await save();setStage('complete')};
function renderComplete(){if(!current)return;$('doneLine').src=current.mysteryArt||current.line||'';$('doneColour').src=current.artwork||current.main||'';$('doneMode').textContent=current.pageMode==='spread'?'Two-page spread':current.orientation==='landscape'?'Single landscape page':'Single portrait page'}
$('viewBookNow').onclick=()=>switchView('bookView');
function renderCompleted(){const a=state.designs.filter(d=>d.complete&&d.artwork),g=$('gallery');g.innerHTML=a.length?a.map(d=>`<div class="galleryItem ${d.orientation==='landscape'||d.pageMode==='spread'?'landscape':''}"><img src="${d.artwork}"><span class="num">#${d.number}</span></div>`).join(''):'<div class="note">No completed artwork yet.</div>'}
function pageCard(inner,label,cls=''){return `<div class="bookSheet"><div class="bookPageMini ${cls}">${inner}</div><div class="pageLabel">${label}</div></div>`}
function spreadCards(d){const src=d.mysteryArt||d.line||'';return `<div class="spreadBook"><div class="spreadHalf left"><img src="${src}"></div><div class="spreadHalf right"><img src="${src}"></div></div>`}
function ensureGallery(){const ids=state.designs.filter(d=>d.complete&&d.artwork).map(d=>String(d.id));const valid=new Set(ids);state.galleryPages=(state.galleryPages||[]).map(p=>Array.from({length:7},(_,i)=>p?.[i]??null).map(x=>x&&valid.has(String(x))?String(x):null));const placed=new Set(state.galleryPages.flat().filter(Boolean));ids.filter(id=>!placed.has(id)).forEach(id=>{let p=state.galleryPages.find(pg=>pg.some(x=>!x));if(!p){p=Array(7).fill(null);state.galleryPages.push(p)}p[p.findIndex(x=>!x)]=id})}
function gallerySlots(page,index,editable=true){return `<div class="galleryA4 ${editable?'editable':''}" data-page="${index}">${page.map((id,slot)=>{const d=id?state.designs.find(x=>String(x.id)===String(id)):null;return `<div class="gallerySlot slot${slot+1}" data-page="${index}" data-slot="${slot}">${d?`<div class="galleryDrop" draggable="true" data-gid="${d.id}"><img src="${d.artwork}"><b>#${d.number}</b></div>`:`<span class="slotHint">Drop image ${slot+1}</span>`}</div>`}).join('')}</div>`}
function renderGalleryBuilder(){ensureGallery();const a=state.designs.filter(d=>d.complete&&d.artwork),used=new Set(state.galleryPages.flat().filter(Boolean).map(String));$('artTray').innerHTML=a.map(d=>`<div class="trayItem ${used.has(String(d.id))?'used':''}" draggable="true" data-gid="${d.id}"><img src="${d.artwork}"><span>#${d.number}</span></div>`).join('');$('galleryBuilder').innerHTML=state.galleryPages.length?state.galleryPages.map((p,i)=>`<div class="galleryBuildPage">${gallerySlots(p,i,true)}<div class="pageLabel">Back page ${i+1}</div><button class="danger small" data-rmp="${i}">Remove page</button></div>`).join(''):'<div class="note">Add a back page when you are ready to arrange the completed artwork.</div>';wireDnD();document.querySelectorAll('[data-rmp]').forEach(b=>b.onclick=async()=>{const i=+b.dataset.rmp;if(state.galleryPages[i]?.some(Boolean)&&!confirm('Remove this back page and return its images to the tray?'))return;state.galleryPages.splice(i,1);await save()})}
$('addGalleryPage').onclick=async()=>{state.galleryPages.push(Array(7).fill(null));await save()};
function removeFromGallery(id){state.galleryPages.forEach(p=>p.forEach((x,i)=>{if(String(x)===String(id))p[i]=null}))}
function wireDnD(){document.querySelectorAll('[draggable][data-gid]').forEach(el=>{el.ondragstart=()=>dragId=String(el.dataset.gid)});document.querySelectorAll('.gallerySlot').forEach(slot=>{slot.ondragover=e=>{e.preventDefault();slot.classList.add('dropReady')};slot.ondragleave=()=>slot.classList.remove('dropReady');slot.ondrop=async e=>{e.preventDefault();slot.classList.remove('dropReady');if(!dragId)return;const p=+slot.dataset.page,s=+slot.dataset.slot,existing=state.galleryPages[p][s];removeFromGallery(dragId);if(existing){let target=state.galleryPages.find(pg=>pg.some(x=>!x));if(!target){target=Array(7).fill(null);state.galleryPages.push(target)}target[target.findIndex(x=>!x)]=existing}state.galleryPages[p][s]=dragId;dragId=null;await save()}})}
function renderBook(){ensureGallery();if($('coverPreview')){$('coverPreview').src=state.cover||'';$('coverPreview').style.display=state.cover?'block':'none'}if($('insidePreview')){$('insidePreview').src=state.insideImage||'';$('insidePreview').style.display=state.insideImage?'block':'none'}renderGalleryBuilder();let html='',pages=0;html+=pageCard(state.cover?`<img src="${state.cover}">`:'<div class="sectionMini">Front cover</div>','Front cover','cover');pages++;const inside=state.insideImage?`<img src="${state.insideImage}">`:`<div class="dedicationMini">${esc(state.insideText).replace(/\n/g,'<br>')}</div>`;html+=pageCard(inside,'Inside page');pages++;state.designs.filter(d=>d.complete).forEach(d=>{html+=pageCard(keyHTMLFor(d),`Design ${d.number} — colour key`);pages++;if(d.pageMode==='spread'){html+=`<div class="bookSheet spreadSheet">${spreadCards(d)}<div class="pageLabel">Design ${d.number} — two-page spread</div></div>`;pages+=2}else{html+=pageCard(`<img src="${d.mysteryArt||d.line||''}">`,`Design ${d.number} — mystery page`,d.orientation==='landscape'?'landscape':'');pages++}});state.galleryPages.forEach((p,i)=>{html+=pageCard(gallerySlots(p,i,false),`Back gallery ${i+1}`,'galleryPage');pages++});$('visualBook').innerHTML=html;$('bookPageCount').textContent=`${pages} pages`;$('bookStructure').innerHTML=`<div class="note"><strong>${state.designs.filter(d=>d.complete).length} completed designs</strong><br>Front cover → inside page → each colour-key page + mystery page/spread → ${state.galleryPages.length} back gallery page${state.galleryPages.length===1?'':'s'}.</div>`}
function renderAll(){renderList();renderCompleted();renderBook()}
$('previewBook').onclick=renderBook;$('printBook').onclick=()=>window.print();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});load();