const $=id=>document.getElementById(id);
const DB='mystery-book-studio-v12';
let current=null,dragId=null;
let state={title:"Pete's Mystery Colouring Book",cover:null,insideText:"Made especially for Pete\n\nFor all the evenings we spend colouring together.",insideImage:null,designs:[],galleryPages:[]};
function db(){return new Promise((r,j)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains('p'))q.result.createObjectStore('p')};q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)})}
async function save(){const d=await db();await new Promise((r,j)=>{const t=d.transaction('p','readwrite');t.objectStore('p').put(state,'main');t.oncomplete=r;t.onerror=()=>j(t.error)});$('saveState').textContent='Saved ✓';renderAll()}
async function load(){try{const d=await db(),v=await new Promise((r,j)=>{const t=d.transaction('p');const q=t.objectStore('p').get('main');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});if(v)state={...state,...v}}catch(e){}state.designs=(state.designs||[]).map((d,i)=>({...d,number:i+1,pageMode:d.pageMode||'single',orientation:d.orientation||'portrait',swatchCount:d.swatchCount||18,codes:d.codes||null,swatchLeft:d.swatchLeft??5,swatchRight:d.swatchRight??95}));state.galleryPages=(state.galleryPages||[]).map(p=>(p||[]).filter(Boolean).map(x=>typeof x==='object'&&x.id?{id:String(x.id),size:x.size||'medium'}:{id:String(x),size:'medium'}));$('bookTitle').value=state.title;$('insideText').value=state.insideText||'';installV18Styles();updateGalleryHelp();renderAll()}
function fileData(f){return new Promise(r=>{const q=new FileReader();q.onload=()=>r(q.result);q.readAsDataURL(f)})}
function img(src){return new Promise((r,j)=>{const i=new Image();i.onload=()=>r(i);i.onerror=j;i.src=src})}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function hex(c){return'#'+c.map(v=>Math.max(0,Math.min(255,Math.round(v))).toString(16).padStart(2,'0')).join('').toUpperCase()}
function switchView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.v===id));if(id==='bookView')renderBook();scrollTo(0,0)}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchView(b.dataset.v));
$('saveBtn').onclick=save;$('bookTitle').oninput=()=>state.title=$('bookTitle').value;$('insideText').oninput=()=>{state.insideText=$('insideText').value;renderBook()};$('backBtn').onclick=()=>switchView('designsView');
$('coverUpload').onchange=async e=>{if(e.target.files?.[0]){state.cover=await fileData(e.target.files[0]);await save()}};$('removeCover').onclick=async()=>{state.cover=null;$('coverUpload').value='';await save()};
$('insideUpload').onchange=async e=>{if(e.target.files?.[0]){state.insideImage=await fileData(e.target.files[0]);await save()}};$('removeInside').onclick=async()=>{state.insideImage=null;$('insideUpload').value='';await save()};
$('newDesign').onclick=async()=>{current={id:Date.now(),number:state.designs.length+1,name:`Design ${state.designs.length+1}`,pageMode:'single',orientation:'portrait',main:null,line:null,swatchSource:null,artwork:null,mysteryArt:null,palette:null,codes:null,swatchCount:18,swatchLeft:5,swatchRight:95,pairApproved:false,paletteApproved:false,pagesApproved:false,complete:false};state.designs.push(current);await save();openCurrent()};
function status(d){return d.complete?'Complete':d.pagesApproved?'Pages approved':d.paletteApproved?'Swatch page approved':d.pairApproved?'Images approved':'Draft'}
function renderList(){const el=$('designList'),done=state.designs.filter(d=>d.complete).length;$('progress').textContent=`${done} of ${state.designs.length||40} complete`;if(!state.designs.length){el.innerHTML='<div class="note">No designs yet.</div>';return}el.innerHTML=state.designs.map(d=>`<div class="design"><div class="thumb">${d.artwork?`<img src="${d.artwork}">`:''}</div><div><strong>#${d.number} ${esc(d.name)}</strong><br><span class="badge ${d.complete?'ok':''}">${status(d)}</span> <span class="badge">${d.pageMode==='spread'?'2-page spread':d.orientation==='landscape'?'Landscape page':'Portrait page'}</span><div class="miniBtns"><button data-open="${d.id}">Open</button><button class="danger" data-del="${d.id}">Remove</button></div></div></div>`).join('');el.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{current=state.designs.find(d=>d.id==b.dataset.open);openCurrent()});el.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(!confirm('Remove this design?'))return;const id=String(b.dataset.del);state.designs=state.designs.filter(d=>String(d.id)!==id);state.designs.forEach((d,i)=>d.number=i+1);state.galleryPages.forEach(p=>{for(let i=p.length-1;i>=0;i--)if(String(p[i].id)===id)p.splice(i,1)});await save()})}
function setStage(s){['upload','palette','pages','complete'].forEach(k=>{$(k+'Stage').classList.toggle('hidden',k!==s);const b=document.querySelector(`.stage[data-s="${k}"]`);b.classList.toggle('active',k===s);b.classList.toggle('done',k==='upload'?current?.pairApproved:k==='palette'?current?.paletteApproved:k==='pages'?current?.pagesApproved:current?.complete)});if(s==='palette')renderPalette();if(s==='pages')renderPages();if(s==='complete')renderComplete()}
function setMode(mode){if(!current)return;current.pageMode=mode;if(mode==='spread')current.orientation='landscape';renderModeButtons();renderPages();save()}
function setOrientation(o){if(!current||current.pageMode==='spread')return;current.orientation=o;renderModeButtons();renderPages();save()}
$('singleBtn').onclick=()=>setMode('single');$('spreadBtn').onclick=()=>setMode('spread');$('portraitBtn').onclick=()=>setOrientation('portrait');$('landscapeBtn').onclick=()=>setOrientation('landscape');
function renderModeButtons(){if(!current)return;$('singleBtn').classList.toggle('selected',current.pageMode!=='spread');$('spreadBtn').classList.toggle('selected',current.pageMode==='spread');$('portraitBtn').classList.toggle('selected',current.orientation!=='landscape'&&current.pageMode!=='spread');$('landscapeBtn').classList.toggle('selected',current.orientation==='landscape'&&current.pageMode!=='spread');$('orientationRow').classList.toggle('muted',current.pageMode==='spread')}
async function openCurrent(){if(!current)return;$('editTitle').textContent=`Design #${current.number}`;$('mainPreview').src=current.main||'';$('linePreview').src=current.line||'';$('swatchPreview').src=current.swatchSource||'';$('swatchCount').value=current.swatchCount||18;$('swatchCountVal').textContent=$('swatchCount').value;$('swatchLeft').value=current.swatchLeft??5;$('swatchRight').value=current.swatchRight??95;renderModeButtons();setStage(current.complete?'complete':current.pagesApproved?'complete':current.paletteApproved?'pages':current.pairApproved?'palette':'upload');switchView('editorView')}
$('mainUpload').onchange=async e=>{if(current&&e.target.files?.[0]){current.main=await fileData(e.target.files[0]);$('mainPreview').src=current.main;checkUploads()}};$('lineUpload').onchange=async e=>{if(current&&e.target.files?.[0]){current.line=await fileData(e.target.files[0]);$('linePreview').src=current.line;checkUploads()}};$('swatchUpload').onchange=async e=>{if(current&&e.target.files?.[0]){current.swatchSource=await fileData(e.target.files[0]);$('swatchPreview').src=current.swatchSource;checkUploads()}};
function checkUploads(){$('approvePair').disabled=!(current?.main&&current?.line&&current?.swatchSource)}
$('approvePair').onclick=async()=>{if(!current?.main||!current?.line||!current?.swatchSource)return;current.artwork=current.main;current.mysteryArt=current.line;current.pairApproved=true;current.paletteApproved=false;current.pagesApproved=false;current.complete=false;current.palette=null;current.codes=null;await save();setStage('palette')};
$('swatchCount').oninput=()=>{$('swatchCountVal').textContent=$('swatchCount').value;if(current)current.swatchCount=+$('swatchCount').value};$('swatchLeft').oninput=()=>{if(current)current.swatchLeft=+$('swatchLeft').value};$('swatchRight').oninput=()=>{if(current)current.swatchRight=+$('swatchRight').value};
function defaultCodes(n){const base=['','2','3','4','5','6','7','8','9','0','a','b','c','d','e','f','g','h'];return Array.from({length:n},(_,i)=>base[i]??String(i+1))}
async function readSwatches(){if(!current?.swatchSource)return;const im=await img(current.swatchSource),n=+($('swatchCount').value||18),l=(current.swatchLeft??5)/100,r=(current.swatchRight??95)/100;const x0=im.naturalWidth*l,x1=im.naturalWidth*r,slot=(x1-x0)/n,c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(im,0,0);const colors=[];for(let i=0;i<n;i++){const cx=x0+slot*(i+.5),cy=im.naturalHeight*.5,rx=Math.max(2,slot*.16),ry=Math.max(2,im.naturalHeight*.08),sx=Math.max(0,Math.floor(cx-rx)),sy=Math.max(0,Math.floor(cy-ry)),sw=Math.max(1,Math.floor(rx*2)),sh=Math.max(1,Math.floor(ry*2)),d=g.getImageData(sx,sy,Math.min(sw,im.naturalWidth-sx),Math.min(sh,im.naturalHeight-sy)).data;let R=0,G=0,B=0,k=0;for(let p=0;p<d.length;p+=4){const rr=d[p],gg=d[p+1],bb=d[p+2];if(rr>250&&gg>250&&bb>250)continue;R+=rr;G+=gg;B+=bb;k++}colors.push(k?[R/k,G/k,B/k]:[245,240,230])}current.palette=colors;current.codes=current.codes?.length===n?current.codes:defaultCodes(n);renderPalette();await save()}
$('readPalette').onclick=readSwatches;
function keyHTMLFor(d){if(!d?.palette?.length)return'';const codes=d.codes||defaultCodes(d.palette.length);return `<div class="keyTitle">COLOUR KEY</div><div class="keySub">Design ${d.number}</div><div class="keyList">${d.palette.map((c,i)=>`<div class="keyRow"><span class="code">${esc(codes[i]||'')}</span><span class="swatchBlock" style="background:${hex(c)}"></span><span class="writeLine"></span></div>`).join('')}</div>`}
function renderPalette(){if(!current?.palette?.length){$('paletteEditor').innerHTML='<div class="note">Upload the base swatch page, set the swatch count and boundaries, then press <strong>Read swatches</strong>.</div>';$('keyPage').innerHTML='';$('approvePalette').disabled=true;return}const codes=current.codes||defaultCodes(current.palette.length);$('paletteEditor').innerHTML=current.palette.map((c,i)=>`<div class="swatchEdit"><span class="swatchBlock big" style="background:${hex(c)}"></span><input data-code="${i}" value="${esc(codes[i])}" aria-label="Code ${i+1}"><span>${hex(c)}</span></div>`).join('');$('paletteEditor').querySelectorAll('[data-code]').forEach(inp=>inp.oninput=()=>{current.codes[+inp.dataset.code]=inp.value;$('keyPage').innerHTML=keyHTMLFor(current)});$('keyPage').innerHTML=keyHTMLFor(current);$('approvePalette').disabled=false}
$('approvePalette').onclick=async()=>{if(!current?.palette?.length)return;current.paletteApproved=true;await save();setStage('pages')};
function renderPages(){if(!current)return;$('leftPage').innerHTML=keyHTMLFor(current);$('rightPageImg').src=current.mysteryArt||current.line||'';$('mysteryPage').classList.toggle('landscape',current.orientation==='landscape'&&current.pageMode!=='spread');$('spreadPreview').classList.toggle('hidden',current.pageMode!=='spread');$('singlePreview').classList.toggle('hidden',current.pageMode==='spread');if(current.pageMode==='spread'){$('spreadLeftImg').src=current.mysteryArt||current.line||'';$('spreadRightImg').src=current.mysteryArt||current.line||'';ensureSpreadStageNote()}}
$('approvePages').onclick=async()=>{current.pagesApproved=true;current.complete=true;await save();setStage('complete')};
function renderComplete(){if(!current)return;$('doneLine').src=current.mysteryArt||current.line||'';$('doneColour').src=current.artwork||current.main||'';$('doneMode').textContent=current.pageMode==='spread'?'Two-page spread':current.orientation==='landscape'?'Single landscape page':'Single portrait page'}
$('viewBookNow').onclick=()=>switchView('bookView');
function renderCompleted(){const a=state.designs.filter(d=>d.complete&&d.artwork),g=$('gallery');g.innerHTML=a.length?a.map(d=>`<div class="galleryItem ${d.orientation==='landscape'||d.pageMode==='spread'?'landscape':''}"><img src="${d.artwork}"><span class="num">#${d.number}</span></div>`).join(''):'<div class="note">No completed artwork yet.</div>'}
function pageCard(inner,label,cls=''){return `<div class="bookSheet"><div class="bookPageMini ${cls}">${inner}</div><div class="pageLabel">${label}</div></div>`}
function spreadPair(left,right,label){return `<div class="spreadSheet v18Facing"><div class="bookPageMini">${left}</div><div class="bookPageMini">${right}</div><div class="pageLabel">${label}</div></div>`}
function artSpread(d){const src=d.mysteryArt||d.line||'';return `<div class="spreadSheet v18Facing"><div class="bookPageMini spreadBg left" style="background-image:url('${src}')"></div><div class="bookPageMini spreadBg right" style="background-image:url('${src}')"></div><div class="pageLabel">Design ${d.number} — two-page mystery spread</div></div>`}
function orientationForGallery(d){return d.orientation==='portrait'&&d.pageMode!=='spread'?'portrait':'landscape'}
function sizeDims(d,size){const portrait=orientationForGallery(d)==='portrait',m=portrait?{small:[3,4],medium:[4,6],large:[6,8]}:{small:[4,3],medium:[6,4],large:[8,6]};return m[size]||m.medium}
function pageArea(page){return page.reduce((t,p)=>{const d=state.designs.find(x=>String(x.id)===String(p.id));if(!d)return t;const [c,r]=sizeDims(d,p.size||'medium');return t+c*r},0)}
function usedGalleryIds(){return new Set(state.galleryPages.flat().map(p=>String(p.id)))}
function galleryTile(pl,editable=true){const d=state.designs.find(x=>String(x.id)===String(pl.id));if(!d)return'';const [cw,rh]=sizeDims(d,pl.size||'medium');return `<div class="mosaicTile" ${editable?'draggable="true"':''} data-gid="${d.id}" style="grid-column:span ${cw};grid-row:span ${rh}"><img src="${d.artwork}"><b>#${d.number}</b>${editable?`<div class="sizeBtns"><button data-size="small" title="Small">S</button><button data-size="medium" title="Medium">M</button><button data-size="large" title="Large">L</button><button data-remove="1" title="Return to tray">×</button></div>`:''}</div>`}
function renderGalleryBuilder(){const used=usedGalleryIds(),available=state.designs.filter(d=>d.complete&&d.artwork&&!used.has(String(d.id)));$('artTray').innerHTML=available.length?available.map(d=>`<div class="trayItem" draggable="true" data-gid="${d.id}"><img src="${d.artwork}"><span>#${d.number} · ${orientationForGallery(d)}</span></div>`).join(''):'<div class="note">All completed artwork is currently placed.</div>';$('galleryBuilder').innerHTML=state.galleryPages.length?state.galleryPages.map((p,i)=>`<div class="galleryBuildPage"><div class="galleryCanvas editable" data-page="${i}">${p.map(pl=>galleryTile(pl,true)).join('')}</div><div class="galleryPageFoot"><span>Back page ${i+1} · ${pageArea(p)}/192 layout units</span><button class="danger small" data-rmp="${i}">Remove page</button></div></div>`).join(''):'<div class="note">Add a back page, then drag artwork onto it. Each image can be Small, Medium or Large.</div>';wireDnD();document.querySelectorAll('[data-rmp]').forEach(b=>b.onclick=async()=>{const i=+b.dataset.rmp;if(state.galleryPages[i]?.length&&!confirm('Return all images on this page to the tray and remove the page?'))return;state.galleryPages.splice(i,1);await save()})}
function removeFromGallery(id){state.galleryPages.forEach(p=>{for(let i=p.length-1;i>=0;i--)if(String(p[i].id)===String(id))p.splice(i,1)})}
function canFit(page,d,size,excludeId=null){let area=0;for(const pl of page){if(excludeId&&String(pl.id)===String(excludeId))continue;const pd=state.designs.find(x=>String(x.id)===String(pl.id));if(pd){const [c,r]=sizeDims(pd,pl.size||'medium');area+=c*r}}const [c,r]=sizeDims(d,size);return area+c*r<=192}
function wireDnD(){document.querySelectorAll('[draggable="true"][data-gid]').forEach(el=>el.ondragstart=e=>{dragId=String(el.dataset.gid);e.dataTransfer.effectAllowed='move'});document.querySelectorAll('.galleryCanvas.editable').forEach(page=>{page.ondragover=e=>{e.preventDefault();page.classList.add('dropReady')};page.ondragleave=()=>page.classList.remove('dropReady');page.ondrop=async e=>{e.preventDefault();page.classList.remove('dropReady');if(!dragId)return;const d=state.designs.find(x=>String(x.id)===dragId);if(!d)return;const pi=+page.dataset.page,target=e.target.closest('.mosaicTile'),size='medium';removeFromGallery(dragId);while(state.galleryPages.length<=pi)state.galleryPages.push([]);const arr=state.galleryPages[pi];if(!canFit(arr,d,size)){alert('That image will not fit on this page at Medium size. Try another page or resize existing images smaller.');renderGalleryBuilder();return}const pl={id:dragId,size};if(target){const tid=String(target.dataset.gid),idx=arr.findIndex(x=>String(x.id)===tid);arr.splice(idx<0?arr.length:idx,0,pl)}else arr.push(pl);await save()}});document.querySelectorAll('.sizeBtns button').forEach(b=>b.onclick=async e=>{e.preventDefault();e.stopPropagation();const tile=b.closest('.mosaicTile'),id=String(tile.dataset.gid);for(const p of state.galleryPages){const pl=p.find(x=>String(x.id)===id);if(!pl)continue;if(b.dataset.remove){p.splice(p.indexOf(pl),1)}else{const d=state.designs.find(x=>String(x.id)===id);if(!canFit(p,d,b.dataset.size,id)){alert('That size will not fit on this page. Make another image smaller or move it to another page.');return}pl.size=b.dataset.size}break}await save()})}
$('addGalleryPage').onclick=async()=>{state.galleryPages.push([]);await save()};
function gallerySheet(page,i){return pageCard(`<div class="galleryCanvas">${page.map(pl=>galleryTile(pl,false)).join('')}</div>`,`Back gallery ${i+1}`,'galleryPage')}
function renderBook(){const completed=state.designs.filter(d=>d.complete);if($('coverPreview')){$('coverPreview').src=state.cover||'';$('coverPreview').style.display=state.cover?'block':'none'}if($('insidePreview')){$('insidePreview').src=state.insideImage||'';$('insidePreview').style.display=state.insideImage?'block':'none'}let html='',pages=0;html+=state.cover?pageCard(`<img src="${state.cover}">`,'Front cover','cover'):pageCard('<div class="sectionMini">Front cover not added</div>','Front cover');pages++;const inside=state.insideImage?`<img src="${state.insideImage}">`:`<div class="dedicationMini">${esc(state.insideText||'').replace(/\n/g,'<br>')}</div>`;html+=pageCard(inside,'Inside page');pages++;completed.forEach(d=>{if(d.pageMode==='spread'){html+=spreadPair('<div class="spacerPage"></div>',`<div class="keyMini">${keyHTMLFor(d)}</div>`,`Design ${d.number} — blank companion + colour key (turn page)`);html+=artSpread(d);pages+=4}else{html+=spreadPair(`<div class="keyMini">${keyHTMLFor(d)}</div>`,`<div class="singleMystery ${d.orientation==='landscape'?'landscape':''}"><img src="${d.mysteryArt||d.line||''}"></div>`,`Design ${d.number} — colour key + mystery page`);pages+=2}});state.galleryPages.forEach((p,i)=>{if(p.length){html+=gallerySheet(p,i);pages++}});$('visualBook').innerHTML=html;$('bookPageCount').textContent=`${pages} pages`;$('bookStructure').innerHTML=`<div class="note"><strong>${completed.length} completed designs</strong><br>For every two-page mystery spread, the app automatically places a blank companion page beside its colour key. When that sheet is turned, the artwork appears uninterrupted across the next two facing pages. No swatch page can land between the two halves.<br><br>Back gallery: ${state.galleryPages.length} custom page${state.galleryPages.length===1?'':'s'} with Small / Medium / Large artwork sizes.</div>`;renderGalleryBuilder()}
function ensureSpreadStageNote(){if($('spreadFixNote'))return;const n=document.createElement('div');n.id='spreadFixNote';n.className='note';n.style.margin='10px 0';n.innerHTML='<strong>Two-page spread pagination:</strong> the colour key will sit on the right-hand page of the preceding spread with a blank companion page on the left. Turn that sheet and the artwork is revealed across the next two facing pages, so nothing interrupts the centre of the picture.';$('spreadPreview').before(n)}
function updateGalleryHelp(){const h=[...document.querySelectorAll('#bookView .card h2')].find(x=>x.textContent.includes('Back gallery'));const note=h?.parentElement?.querySelector('.note');if(note)note.innerHTML='<strong>Flexible gallery:</strong> add as many A4 pages as you need. Drag completed artwork onto a page, then choose S, M or L on each image. Portrait and landscape artwork have their own matching preset proportions. Mix sizes freely; there is no fixed seven-image layout.'}
function installV18Styles(){if($('v18Style'))return;const s=document.createElement('style');s.id='v18Style';s.textContent=`.galleryA4,.gallerySlot{display:none!important}.galleryCanvas{width:100%;aspect-ratio:210/297;background:#fff;border:1px solid var(--line);border-radius:9px;padding:8px;display:grid;grid-template-columns:repeat(12,1fr);grid-template-rows:repeat(16,1fr);grid-auto-flow:dense;gap:5px;overflow:hidden}.galleryCanvas.dropReady{outline:3px dashed var(--accent);outline-offset:2px}.mosaicTile{position:relative;min-width:0;min-height:0;border:1px solid #ddd;border-radius:7px;background:#fafafa;overflow:hidden}.mosaicTile img{width:100%;height:100%;object-fit:contain;display:block}.mosaicTile>b{position:absolute;left:4px;bottom:4px;background:#ffffffe8;border-radius:5px;padding:2px 5px;font-size:9px}.sizeBtns{position:absolute;right:3px;top:3px;display:flex;gap:2px;background:#ffffffdd;padding:2px;border-radius:6px}.sizeBtns button{min-height:24px;min-width:25px;padding:2px 5px;font-size:9px;border-radius:5px}.galleryPageFoot{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-top:5px;font-size:10px;color:var(--muted)}.v18Facing{display:grid;grid-template-columns:1fr 1fr;gap:4px;grid-column:span 2}.v18Facing .bookPageMini{width:100%}.spreadBg{background-size:200% 100%;background-repeat:no-repeat;padding:0}.spreadBg.left{background-position:left center}.spreadBg.right{background-position:right center}.keyMini{width:100%;height:100%;overflow:hidden}.singleMystery{width:100%;height:100%;display:flex;align-items:center;justify-content:center}.singleMystery img{width:100%;height:100%;object-fit:contain}.singleMystery.landscape img{transform:rotate(0deg)}.spacerPage{width:100%;height:100%;background:#fff}.galleryBuildPage{max-width:440px}.trayItem span{display:block}.artTray .note{min-width:220px}@media(max-width:760px){.v18Facing{grid-column:span 2}.sizeBtns button{min-width:23px}}`;document.head.appendChild(s)}
function renderAll(){renderList();renderCompleted();renderBook()}
$('previewBook').onclick=renderBook;$('printBook').onclick=()=>window.print();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});load();