const $=id=>document.getElementById(id);
let state={title:"Pete's Mystery Colouring Book",dedication:"Made especially for Pete\n\nFor all the evenings we spend colouring together.",cover:null,designs:[],galleryPages:[]},current=null;
const DB='mystery-book-studio-v12';
function db(){return new Promise((r,j)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains('p'))q.result.createObjectStore('p')};q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)})}
async function save(){const d=await db();await new Promise((r,j)=>{const t=d.transaction('p','readwrite');t.objectStore('p').put(state,'main');t.oncomplete=r;t.onerror=()=>j(t.error)});$('saveState').textContent='Saved ✓';renderAll()}
async function load(){try{const d=await db(),v=await new Promise((r,j)=>{const t=d.transaction('p');const q=t.objectStore('p').get('main');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});if(v)state={cover:null,galleryPages:[],...v}}catch(e){}state.designs=(state.designs||[]).map(d=>({...d,orientation:d.orientation||'portrait',codes:d.codes||null,swatchLeft:d.swatchLeft??8,swatchRight:d.swatchRight??92,mysterySplit:d.mysterySplit??88}));$('bookTitle').value=state.title||"Pete's Mystery Colouring Book";$('dedication').value=state.dedication||'';renderAll()}
function fileData(f){return new Promise(r=>{const q=new FileReader();q.onload=()=>r(q.result);q.readAsDataURL(f)})}
function img(src){return new Promise((r,j)=>{const i=new Image();i.onload=()=>r(i);i.onerror=j;i.src=src})}
function hex(c){return'#'+c.map(v=>Math.round(v).toString(16).padStart(2,'0')).join('').toUpperCase()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function switchView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.v===id));if(id==='bookView')renderBook();scrollTo(0,0)}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchView(b.dataset.v));
$('backBtn').onclick=()=>switchView('designsView');$('saveBtn').onclick=save;$('bookTitle').oninput=()=>state.title=$('bookTitle').value;$('dedication').oninput=()=>{state.dedication=$('dedication').value;renderBook()};
$('newDesign').onclick=async()=>{const n=state.designs.length+1;current={id:Date.now(),number:n,name:`Design ${n}`,orientation:'portrait',colour:null,line:null,artwork:null,mysteryArt:null,paletteCrop:null,mysterySplit:88,swatchLeft:8,swatchRight:92,swatchCount:18,codes:null,palette:null,pairApproved:false,paletteApproved:false,pagesApproved:false,complete:false};state.designs.push(current);await save();openCurrent()};
function status(d){return d.complete?'Complete':d.pagesApproved?'Pages approved':d.paletteApproved?'Colour key approved':d.pairApproved?'Images paired':'Draft'}
function renderList(){const el=$('designList');$('progress').textContent=`${state.designs.filter(d=>d.complete).length} of 40 complete`;if(!state.designs.length){el.className='note';el.textContent='No designs yet.';return}el.className='';el.innerHTML='';state.designs.forEach(d=>{const x=document.createElement('div');x.className='design';x.innerHTML=`<div class="thumb">${d.artwork?`<img src="${d.artwork}">`:''}</div><div><strong>#${d.number} ${esc(d.name)}</strong><br><span class="badge ${d.complete?'ok':''}">${status(d)}</span> <span class="badge">${d.orientation==='landscape'?'Landscape':'Portrait'}</span><div style="display:flex;gap:7px;margin-top:7px"><button data-o="${d.id}">Open</button><button class="danger" data-d="${d.id}">Remove</button></div></div>`;el.appendChild(x)});el.querySelectorAll('[data-o]').forEach(b=>b.onclick=()=>{current=state.designs.find(d=>d.id==b.dataset.o);openCurrent()});el.querySelectorAll('[data-d]').forEach(b=>b.onclick=async()=>{if(!confirm('Remove this design?'))return;state.designs=state.designs.filter(d=>d.id!=b.dataset.d);state.designs.forEach((d,i)=>d.number=i+1);state.galleryPages=[];await save()})}
function renderOrientationButtons(){$('portraitBtn').classList.toggle('selected',current?.orientation!=='landscape');$('landscapeBtn').classList.toggle('selected',current?.orientation==='landscape')}
async function setOrientation(v){if(!current)return;current.orientation=v;renderOrientationButtons();renderPages();await save()}
$('portraitBtn').onclick=()=>setOrientation('portrait');$('landscapeBtn').onclick=()=>setOrientation('landscape');
function setStage(s){['upload','palette','pages','complete'].forEach(k=>{$(k+'Stage').classList.toggle('hidden',k!==s);const b=document.querySelector(`.stage[data-s="${k}"]`);b.classList.toggle('active',k===s);b.classList.toggle('done',k==='upload'?current?.pairApproved:k==='palette'?current?.paletteApproved:k==='pages'?current?.pagesApproved:current?.complete)});if(s==='palette')renderPaletteStage();if(s==='pages')renderPages();if(s==='complete')renderComplete()}
async function openCurrent(){if(!current)return;current.orientation=current.orientation||'portrait';current.mysterySplit=current.mysterySplit??88;current.swatchLeft=current.swatchLeft??8;current.swatchRight=current.swatchRight??92;$('editTitle').textContent=`Design #${current.number}`;$('colourPreview').src=current.colour||'';$('linePreview').src=current.line||'';$('mysterySplit').value=current.mysterySplit;$('mysterySplitVal').textContent=current.mysterySplit+'%';$('swatchCount').value=current.swatchCount||18;$('swatchCountVal').textContent=$('swatchCount').value;$('swatchLeft').value=current.swatchLeft;$('swatchRight').value=current.swatchRight;renderOrientationButtons();drawMysterySplit();setStage(current.complete?'complete':current.pagesApproved?'complete':current.paletteApproved?'pages':current.pairApproved?'palette':'upload');switchView('editorView')}
$('colourUpload').onchange=async e=>{if(!current||!e.target.files?.[0])return;current.colour=await fileData(e.target.files[0]);$('colourPreview').src=current.colour;checkPair()};
$('lineUpload').onchange=async e=>{if(!current||!e.target.files?.[0])return;current.line=await fileData(e.target.files[0]);$('linePreview').src=current.line;drawMysterySplit();checkPair()};
function checkPair(){$('approvePair').disabled=!(current?.colour&&current?.line)}
$('mysterySplit').oninput=()=>{if(!current)return;current.mysterySplit=+$('mysterySplit').value;$('mysterySplitVal').textContent=current.mysterySplit+'%';drawMysterySplit()};
async function drawMysterySplit(){if(!current?.line)return;const im=await img(current.line),c=$('mysterySplitCanvas'),w=Math.min(800,im.naturalWidth),h=Math.round(w*im.naturalHeight/im.naturalWidth);c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);$('mysteryDivider').style.top=(current.mysterySplit??88)+'%'}
async function cropTop(src,pct){const im=await img(src),cut=Math.round(im.naturalHeight*pct/100),c=document.createElement('canvas');c.width=im.naturalWidth;c.height=cut;c.getContext('2d').drawImage(im,0,0,im.naturalWidth,cut,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.97)}
async function cropBottom(src,pct){const im=await img(src),cut=Math.round(im.naturalHeight*pct/100),c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight-cut;c.getContext('2d').drawImage(im,0,cut,im.naturalWidth,im.naturalHeight-cut,0,0,c.width,c.height);return c.toDataURL('image/png')}
$('approvePair').onclick=async()=>{if(!current?.colour||!current?.line)return;const split=current.mysterySplit??88;current.mysteryArt=await cropTop(current.line,split);current.paletteCrop=await cropBottom(current.line,split);current.artwork=await cropTop(current.colour,split);current.pairApproved=true;current.paletteApproved=false;current.pagesApproved=false;current.complete=false;current.palette=null;current.codes=null;await save();setStage('palette')};
$('swatchCount').oninput=()=>{$('swatchCountVal').textContent=$('swatchCount').value;if(current)current.swatchCount=+$('swatchCount').value};$('swatchLeft').oninput=()=>{if(current)current.swatchLeft=+$('swatchLeft').value;renderSwatchCrop()};$('swatchRight').oninput=()=>{if(current)current.swatchRight=+$('swatchRight').value;renderSwatchCrop()};
async function renderSwatchCrop(){if(!current?.paletteCrop)return;const im=await img(current.paletteCrop),c=$('swatchCanvas'),w=Math.min(800,im.naturalWidth),h=Math.max(50,Math.round(im.naturalHeight*w/im.naturalWidth));c.width=w;c.height=h;const g=c.getContext('2d');g.drawImage(im,0,0,w,h);const l=w*(current.swatchLeft??8)/100,r=w*(current.swatchRight??92)/100;g.strokeStyle='#ff2d55';g.lineWidth=3;g.strokeRect(l,2,Math.max(2,r-l),h-4)}
function defaultCodes(n){const base=['','2','3','4','5','6','7','8','9','0','a','b','c','d','e','f','g','h'];return Array.from({length:n},(_,i)=>base[i]??String(i+1))}
async function readExactSwatches(){if(!current?.paletteCrop)return;const im=await img(current.paletteCrop),n=+($('swatchCount').value||18),l=(current.swatchLeft??8)/100,r=(current.swatchRight??92)/100;const x0=im.naturalWidth*l,x1=im.naturalWidth*r,slot=(x1-x0)/n,c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(im,0,0);const colors=[];for(let i=0;i<n;i++){const cx=x0+slot*(i+.5),cy=im.naturalHeight*.48,radX=Math.max(2,slot*.18),radY=Math.max(2,im.naturalHeight*.14),d=g.getImageData(Math.max(0,Math.floor(cx-radX)),Math.max(0,Math.floor(cy-radY)),Math.max(1,Math.floor(radX*2)),Math.max(1,Math.floor(radY*2))).data;let rr=0,gg=0,bb=0,k=0;for(let p=0;p<d.length;p+=4){const R=d[p],G=d[p+1],B=d[p+2];if(R>248&&G>248&&B>248)continue;rr+=R;gg+=G;bb+=B;k++}colors.push(k?[rr/k,gg/k,bb/k]:[250,245,235])}current.palette=colors;current.codes=current.codes?.length===n?current.codes:defaultCodes(n);renderPaletteStage();await save()}
$('readPalette').onclick=readExactSwatches;
function keyHTMLFor(d){if(!d?.palette?.length)return'';const codes=d.codes||defaultCodes(d.palette.length);return `<h3 style="text-align:center;margin:2px 0 9px">COLOUR KEY — #${d.number}</h3>`+d.palette.map((c,i)=>`<div class="keyRow"><b style="text-align:center">${esc(codes[i]||'')}</b><span class="dot" style="background:${hex(c)};width:30px;height:30px"></span><div class="line"></div></div>`).join('')}
function renderPaletteStage(){renderSwatchCrop();if(!current?.palette?.length){$('paletteEditor').innerHTML='<div class="note">Set the left/right bounds around the swatch strip, choose the swatch count, then press <strong>Read exact swatches</strong>.</div>';$('keyPage').innerHTML='';$('approvePalette').disabled=true;return}const codes=current.codes||defaultCodes(current.palette.length);$('paletteEditor').innerHTML=current.palette.map((c,i)=>`<div class="swatchEdit"><span class="dot big" style="background:${hex(c)}"></span><input data-code="${i}" value="${esc(codes[i])}" aria-label="Code for swatch ${i+1}"><span>${hex(c)}</span></div>`).join('');$('paletteEditor').querySelectorAll('[data-code]').forEach(inp=>inp.oninput=()=>{current.codes[+inp.dataset.code]=inp.value;$('keyPage').innerHTML=keyHTMLFor(current)});$('keyPage').innerHTML=keyHTMLFor(current);$('approvePalette').disabled=false}
$('approvePalette').onclick=async()=>{if(!current?.palette?.length)return;current.paletteApproved=true;await save();setStage('pages')};
function renderPages(){if(!current)return;$('leftPage').innerHTML=keyHTMLFor(current);$('leftPage').classList.remove('landscape');$('rightPageImg').src=current.mysteryArt||current.line||'';$('mysteryPage').classList.toggle('landscape',current.orientation==='landscape')}
$('approvePages').onclick=async()=>{current.pagesApproved=true;current.complete=true;state.galleryPages=[];await save();setStage('complete')};
function renderComplete(){if(!current)return;$('doneLine').src=current.mysteryArt||current.line||'';$('doneColour').src=current.artwork||current.colour||''}
$('viewBookNow').onclick=()=>switchView('bookView');
function renderGallery(){const g=$('gallery'),a=state.designs.filter(d=>d.complete&&d.artwork);g.innerHTML=a.length?a.map(d=>`<div class="galleryItem ${d.orientation==='landscape'?'landscape':''}"><img src="${d.artwork}"><span class="num">#${d.number}</span></div>`).join(''):'<div class="note">No completed designs yet.</div>'}
function pageCard(inner,label,cls=''){return `<div class="bookSheet"><div class="bookPageMini ${cls}">${inner}</div><div class="pageLabel">${label}</div></div>`}
function ensureGalleryPages(){const ids=state.designs.filter(d=>d.complete&&d.artwork).map(d=>d.id);const used=new Set((state.galleryPages||[]).flat());const missing=ids.filter(id=>!used.has(id));if(!state.galleryPages?.length)state.galleryPages=[];while(missing.length){state.galleryPages.push(missing.splice(0,6))}state.galleryPages=state.galleryPages.map(p=>p.filter(id=>ids.includes(id))).filter(p=>p.length)}
function gallerySheet(pageIds,pageNo){const items=pageIds.map(id=>state.designs.find(d=>d.id===id)).filter(Boolean);return pageCard(`<div class="galleryA4" data-page="${pageNo-1}">${items.map(d=>`<div class="galleryDrop ${d.orientation==='landscape'?'wide':''}" draggable="true" data-gid="${d.id}"><img src="${d.artwork}"><b>#${d.number}</b></div>`).join('')}</div>`,`Completed artwork ${pageNo}`,'completedGrid')}
function renderGalleryBuilder(){ensureGalleryPages();const a=state.designs.filter(d=>d.complete&&d.artwork),tray=$('artTray'),builder=$('galleryBuilder');tray.innerHTML=a.map(d=>`<div class="trayItem" draggable="true" data-gid="${d.id}"><img src="${d.artwork}"><span>#${d.number}</span></div>`).join('');builder.innerHTML=state.galleryPages.length?state.galleryPages.map((p,i)=>`<div class="galleryBuildPage"><div class="galleryA4 editable" data-page="${i}">${p.map(id=>{const d=state.designs.find(x=>x.id===id);return d?`<div class="galleryDrop ${d.orientation==='landscape'?'wide':''}" draggable="true" data-gid="${d.id}"><img src="${d.artwork}"><b>#${d.number}</b></div>`:''}).join('')}</div><div class="pageLabel">Back page ${i+1}</div></div>`).join(''):'<div class="note">Complete designs to build the back gallery.</div>';wireDnD()}
let dragId=null;function wireDnD(){document.querySelectorAll('[draggable="true"][data-gid]').forEach(el=>el.ondragstart=e=>{dragId=+el.dataset.gid;e.dataTransfer.effectAllowed='move'});document.querySelectorAll('.galleryA4.editable').forEach(page=>{page.ondragover=e=>{e.preventDefault();page.classList.add('dropReady')};page.ondragleave=()=>page.classList.remove('dropReady');page.ondrop=async e=>{e.preventDefault();page.classList.remove('dropReady');if(!dragId)return;const pi=+page.dataset.page;state.galleryPages.forEach(p=>{const x=p.indexOf(dragId);if(x>=0)p.splice(x,1)});state.galleryPages=state.galleryPages.filter(p=>p.length);while(state.galleryPages.length<=pi)state.galleryPages.push([]);if(state.galleryPages[pi].length>=6){alert('This page already has 6 images. Move one out first.');renderGalleryBuilder();return}state.galleryPages[pi].push(dragId);await save();renderGalleryBuilder();renderBook()}})}
$('addGalleryPage').onclick=async()=>{ensureGalleryPages();state.galleryPages.push([]);await save();renderGalleryBuilder()};
function renderBook(){const a=state.designs.filter(d=>d.complete);ensureGalleryPages();if($('coverPreview')){$('coverPreview').src=state.cover||'';$('coverPreview').style.display=state.cover?'block':'none'}let html='',pages=0;if(state.cover){html+=pageCard(`<img src="${state.cover}">`,'Front cover','cover');pages++}else{html+=pageCard('<div class="sectionMini">Front cover not added</div>','Front cover');pages++}html+=pageCard(`<div class="dedicationMini">${esc(state.dedication||'')}</div>`,'Dedication');pages++;a.forEach(d=>{html+=pageCard(`<div style="width:100%;height:100%;overflow:hidden">${keyHTMLFor(d)}</div>`,`#${d.number} Colour key — Portrait`);html+=pageCard(`<img src="${d.mysteryArt||d.line||''}">`,`#${d.number} Mystery page — ${d.orientation==='landscape'?'Landscape':'Portrait'}`,d.orientation==='landscape'?'landscape':'');pages+=2});state.galleryPages.forEach((p,i)=>{if(p.length){html+=gallerySheet(p,i+1);pages++}});$('visualBook').innerHTML=html;$('bookPageCount').textContent=`${pages} page${pages===1?'':'s'}`;$('bookStructure').innerHTML=`<div class="note"><strong>${a.length} completed design${a.length===1?'':'s'}</strong><br>${state.cover?'Front cover added':'Front cover still needed'}<br>Dedication<br>${a.map(d=>`#${d.number} Portrait colour key → ${d.orientation==='landscape'?'Landscape':'Portrait'} mystery page`).join('<br>')}<br>Back gallery: ${state.galleryPages.filter(p=>p.length).length} page(s), max 6 images each.</div>`;renderGalleryBuilder()}
function renderAll(){renderList();renderGallery();renderBook()}
$('coverUpload').onchange=async e=>{if(!e.target.files?.[0])return;state.cover=await fileData(e.target.files[0]);await save()};$('removeCover').onclick=async()=>{state.cover=null;$('coverUpload').value='';await save()};$('previewBook').onclick=renderBook;$('printBook').onclick=()=>window.print();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});load();