const $=id=>document.getElementById(id);
let designs=JSON.parse(localStorage.getItem('mbs-designs')||'[]');
let current=null,sourceImg=null,artImg=null,lastLabels=null,lastComps=[];
const cvs={source:$('source'),artwork:$('artwork'),paletteCrop:$('paletteCrop'),segmented:$('segmented'),mystery:$('mystery'),final:$('finalCanvas')};
const ctx=Object.fromEntries(Object.entries(cvs).map(([k,v])=>[k,v.getContext('2d',{willReadFrequently:true})]));
function migrate(d){d.source=d.source||d.original;d.original=d.original||d.source;d.stage=d.stage||'split';d.splitPct=d.splitPct||80;d.artwork=d.artwork||null;d.paletteCrop=d.paletteCrop||null;d.palette=d.palette||null;d.keyApproved=!!d.keyApproved;d.lineApproved=!!d.lineApproved;d.finalApproved=d.status==='approved'||!!d.finalApproved;d.status=d.finalApproved?'complete':d.lineApproved?'line approved':d.keyApproved?'key approved':d.artwork?'separated':'draft';return d}designs=designs.map(migrate);
function save(){try{localStorage.setItem('mbs-designs',JSON.stringify(designs))}catch(e){alert('This project is getting large. Please remove unused drafts before adding more images.')}renderList();renderGallery();renderStructure()}
function switchView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===id));scrollTo(0,0)}document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>switchView(t.dataset.view));$('backLibrary').onclick=()=>switchView('libraryView');
function codeFor(i){if($('codeStyle').value==='numbers')return String(i+1);let n=i,s='';do{s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)-1}while(n>=0);return s}
function hex(c){return '#'+c.map(x=>Math.round(x).toString(16).padStart(2,'0')).join('').toUpperCase()}
$('upload').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{let n=designs.length+1;designs.push(migrate({id:Date.now(),number:n,name:`Design ${n}`,source:r.result,original:r.result,aspect:im.width/im.height,status:'draft'}));save();openDesign(designs.at(-1).id)};im.src=r.result};r.readAsDataURL(f)};
function deleteDesign(id){const d=designs.find(x=>x.id===id);if(!d)return;if(!confirm(`Remove #${d.number} ${d.name}?`))return;designs=designs.filter(x=>x.id!==id);designs.forEach((x,i)=>{x.number=i+1;if(/^Design \d+$/.test(x.name))x.name=`Design ${i+1}`});if(current?.id===id){current=null;switchView('libraryView')}save()}
function progressText(d){if(d.finalApproved)return'Complete';if(d.lineApproved)return'Line art approved';if(d.keyApproved)return'Colour key approved';if(d.artwork)return'Image separated';return'Draft'}
function renderList(){const el=$('designList'),done=designs.filter(d=>d.finalApproved).length;$('progress').textContent=`${done} of 40 designs complete`;if(!designs.length){el.className='empty';el.textContent='No artwork added yet.';return}el.className='';el.innerHTML='';designs.forEach(d=>{let x=document.createElement('div');x.className='design';x.innerHTML=`<div class="thumb"><img src="${d.artwork||d.source}"></div><div><strong>#${d.number} ${d.name}</strong><br><span class="badge ${d.finalApproved?'approved':d.artwork?'review':''}">${progressText(d)}</span><small>${d.palette?d.palette.length+' colours • ':''}${d.aspect>1.12?'Landscape':d.aspect<.88?'Portrait':'Square'}</small><div style="display:flex;gap:8px;margin-top:7px"><button data-open="${d.id}">Continue</button><button data-delete="${d.id}" class="danger">Remove</button></div></div>`;el.appendChild(x)});el.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openDesign(Number(b.dataset.open)));el.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteDesign(Number(b.dataset.delete)))}
function loadImage(src){return new Promise((res,rej)=>{let im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=src})}
async function openDesign(id){current=designs.find(d=>d.id===id);if(!current)return;current=migrate(current);$('editTitle').textContent=`Page Editor — #${current.number}`;$('split').value=current.splitPct||80;$('splitVal').textContent=`${$('split').value}%`;$('colors').value=current.palette?.length||15;$('colorsVal').textContent=$('colors').value;sourceImg=await loadImage(current.source);drawSource();if(current.artwork){artImg=await loadImage(current.artwork);drawImageFit(artImg,cvs.artwork,ctx.artwork,700);if(current.paletteCrop){let p=await loadImage(current.paletteCrop);drawImageFit(p,cvs.paletteCrop,ctx.paletteCrop,700)}}if(current.palette){renderPalette();renderKeyPage()}if(current.mystery){let m=await loadImage(current.mystery);drawImageFit(m,cvs.mystery,ctx.mystery,700);drawImageFit(m,cvs.final,ctx.final,700)}showStage(current.finalApproved?'final':current.lineApproved?'final':current.keyApproved?'line':current.artwork?'key':'split');switchView('editorView')}
function drawImageFit(im,canvas,c,wmax){let sc=Math.min(1,wmax/im.width);canvas.width=Math.round(im.width*sc);canvas.height=Math.round(im.height*sc);c.clearRect(0,0,canvas.width,canvas.height);c.drawImage(im,0,0,canvas.width,canvas.height)}
function drawSource(){drawImageFit(sourceImg,cvs.source,ctx.source,800);updateDivider();previewSplit()}
function updateDivider(){let p=Number($('split').value);$('splitVal').textContent=`${p}%`;$('dividerLine').style.top=p+'%'}
function previewSplit(){if(!sourceImg)return;let p=Number($('split').value)/100,w=sourceImg.naturalWidth,h=sourceImg.naturalHeight,cut=Math.round(h*p);let scale=Math.min(1,700/w),aw=Math.round(w*scale),ah=Math.round(cut*scale),ph=Math.max(1,Math.round((h-cut)*scale));cvs.artwork.width=aw;cvs.artwork.height=ah;ctx.artwork.drawImage(sourceImg,0,0,w,cut,0,0,aw,ah);cvs.paletteCrop.width=aw;cvs.paletteCrop.height=ph;ctx.paletteCrop.drawImage(sourceImg,0,cut,w,h-cut,0,0,aw,ph)}
$('split').oninput=()=>{updateDivider();previewSplit()};
$('approveSplit').onclick=()=>{if(!current||!sourceImg)return;let p=Number($('split').value)/100,w=sourceImg.naturalWidth,h=sourceImg.naturalHeight,cut=Math.round(h*p);let a=document.createElement('canvas');a.width=w;a.height=cut;a.getContext('2d').drawImage(sourceImg,0,0,w,cut,0,0,w,cut);let pc=document.createElement('canvas');pc.width=w;pc.height=h-cut;pc.getContext('2d').drawImage(sourceImg,0,cut,w,h-cut,0,0,w,h-cut);current.splitPct=Math.round(p*100);current.artwork=a.toDataURL('image/jpeg',.94);current.original=current.artwork;current.paletteCrop=pc.toDataURL('image/png');current.aspect=w/cut;current.palette=null;current.keyApproved=false;current.lineApproved=false;current.finalApproved=false;current.mystery=null;current.status='separated';save();artImg=new Image();artImg.onload=()=>showStage('key');artImg.src=current.artwork};
function showStage(s){['split','key','line','final'].forEach(k=>{$(k+'Stage').classList.toggle('hidden',k!==s);let b=document.querySelector(`.stage[data-stage="${k}"]`);b.classList.toggle('active',k===s);let done=k==='split'?!!current.artwork:k==='key'?current.keyApproved:k==='line'?current.lineApproved:current.finalApproved;b.classList.toggle('done',done)});if(s==='key'&&current.palette){renderPalette();renderKeyPage()}if(s==='final')renderFinalPalette()}
$('colors').oninput=()=>{$('colorsVal').textContent=$('colors').value};
function collectPalettePixels(imageData){let a=[],d=imageData.data;for(let i=0;i<d.length;i+=16){let r=d[i],g=d[i+1],b=d[i+2],max=Math.max(r,g,b),min=Math.min(r,g,b),ch=max-min,lum=(r+g+b)/3;if(lum>242)continue;if(lum<35&&ch<12){if(Math.random()<.08)a.push([r,g,b]);continue}if(ch<10&&lum>190)continue;a.push([r,g,b])}return a}
function kmeansSamples(samples,k){if(!samples.length)return[];let C=[];for(let i=0;i<k;i++)C.push(samples[Math.floor((i+.5)*samples.length/k)%samples.length].slice());for(let z=0;z<9;z++){let sums=Array.from({length:k},()=>[0,0,0,0]);for(const q of samples){let bi=0,bd=1e20;for(let c=0;c<k;c++){let dr=q[0]-C[c][0],dg=q[1]-C[c][1],db=q[2]-C[c][2],dd=dr*dr+dg*dg+db*db;if(dd<bd){bd=dd;bi=c}}let s=sums[bi];s[0]+=q[0];s[1]+=q[1];s[2]+=q[2];s[3]++}for(let c=0;c<k;c++)if(sums[c][3])C[c]=sums[c].slice(0,3).map(x=>x/sums[c][3])}return C.sort((a,b)=>((a[0]+a[1]+a[2])-(b[0]+b[1]+b[2])))}
$('extractPalette').onclick=()=>{if(!current?.paletteCrop)return alert('Approve the image/palette separation first.');let im=ctx.paletteCrop.getImageData(0,0,cvs.paletteCrop.width,cvs.paletteCrop.height),samples=collectPalettePixels(im),k=Number($('colors').value);current.palette=kmeansSamples(samples,k);current.keyApproved=false;current.lineApproved=false;current.finalApproved=false;current.mystery=null;current.status='separated';renderPalette();renderKeyPage();$('approveKey').disabled=false;save()};
function renderPalette(){if(!current?.palette)return;$('palette').innerHTML=current.palette.map((c,i)=>`<span class="sw"><span class="dot" style="background:${hex(c)}"></span><b>${codeFor(i)}</b> ${hex(c)}</span>`).join('');$('approveKey').disabled=false}
function renderKeyPage(){if(!current?.palette)return;$('keyPage').innerHTML=`<h3 style="text-align:center;margin:3px 0 10px">COLOUR KEY — #${current.number}</h3>`+current.palette.map((c,i)=>`<div class="keyRow"><div class="keyCode">${codeFor(i)}</div><div class="keySwatch" style="background:${hex(c)}"></div><div class="writeLine"></div></div>`).join('')}
$('codeStyle').onchange=()=>{renderPalette();renderKeyPage();renderFinalPalette()};
$('approveKey').onclick=()=>{if(!current?.palette?.length)return;current.keyApproved=true;current.status='key approved';current.lineApproved=false;current.finalApproved=false;save();showStage('line')};
function nearest(c,pal){let bi=0,bd=1e20;for(let j=0;j<pal.length;j++){let q=pal[j],dr=c[0]-q[0],dg=c[1]-q[1],db=c[2]-q[2],d=dr*dr+dg*dg+db*db;if(d<bd){bd=d;bi=j}}return bi}
function modePass(L,w,h){let O=L.slice();for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){let counts=new Map();for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++){let v=L[(y+yy)*w+x+xx];counts.set(v,(counts.get(v)||0)+1)}let best=L[y*w+x],n=0;for(const [v,c] of counts)if(c>n){best=v;n=c}if(n>=5)O[y*w+x]=best}return O}
function components(L,w,h,minArea){let seen=new Uint8Array(L.length),q=new Int32Array(L.length),all=[];function flood(st){let lab=L[st],a=0,b=0,pts=[],sx=0,sy=0,minx=w,maxx=0,miny=h,maxy=0;q[b++]=st;seen[st]=1;while(a<b){let i=q[a++],x=i%w,y=i/w|0;pts.push(i);sx+=x;sy+=y;minx=Math.min(minx,x);maxx=Math.max(maxx,x);miny=Math.min(miny,y);maxy=Math.max(maxy,y);for(const n of [x?i-1:-1,x<w-1?i+1:-1,y?i-w:-1,y<h-1?i+w:-1])if(n>=0&&!seen[n]&&L[n]===lab){seen[n]=1;q[b++]=n}}return{lab,pts,size:b,cx:sx/b,cy:sy/b,minx,maxx,miny,maxy}}for(let i=0;i<L.length;i++)if(!seen[i])all.push(flood(i));for(const c of all)if(c.size<minArea){let count=new Map();for(const i of c.pts){let x=i%w,y=i/w|0;for(const n of [x?i-1:-1,x<w-1?i+1:-1,y?i-w:-1,y<h-1?i+w:-1])if(n>=0&&L[n]!==c.lab)count.set(L[n],(count.get(L[n])||0)+1)}let best=c.lab,bn=0;for(const [v,n]of count)if(n>bn){best=v;bn=n}for(const i of c.pts)L[i]=best}seen.fill(0);all=[];for(let i=0;i<L.length;i++)if(!seen[i])all.push(flood(i));return all}
function safePoint(c,L,w,h){let best={x:Math.round(c.cx),y:Math.round(c.cy),r:0},step=Math.max(1,Math.floor(Math.min(c.maxx-c.minx,c.maxy-c.miny)/12));for(let y=c.miny;y<=c.maxy;y+=step)for(let x=c.minx;x<=c.maxx;x+=step){if(L[y*w+x]!==c.lab)continue;let r=0;outer:for(r=1;r<18;r++){for(let xx=-r;xx<=r;xx++)if(L[(Math.max(0,y-r))*w+Math.max(0,Math.min(w-1,x+xx))]!==c.lab||L[Math.min(h-1,y+r)*w+Math.max(0,Math.min(w-1,x+xx))]!==c.lab)break outer;for(let yy=-r;yy<=r;yy++)if(L[Math.max(0,Math.min(h-1,y+yy))*w+Math.max(0,x-r)]!==c.lab||L[Math.max(0,Math.min(h-1,y+yy))*w+Math.min(w-1,x+r)]!==c.lab)break outer}if(r>best.r)best={x,y,r}}return best}
$('buildLine').onclick=async()=>{if(!current?.keyApproved||!current.palette)return alert('Approve the Colour Key first.');$('buildLine').disabled=true;$('lineStatus').innerHTML='<small>Simplifying texture into colouring regions…</small>';artImg=await loadImage(current.artwork);let detail=$('detail').value,targetW=detail==='simple'?360:detail==='standard'?440:520,scale=Math.min(1,targetW/artImg.width),w=Math.round(artImg.width*scale),h=Math.round(artImg.height*scale),t=document.createElement('canvas');t.width=w;t.height=h;let tc=t.getContext('2d',{willReadFrequently:true});tc.filter=detail==='simple'?'blur(3.5px)':detail==='standard'?'blur(2.5px)':'blur(1.5px)';tc.drawImage(artImg,0,0,w,h);let data=tc.getImageData(0,0,w,h).data,L=new Uint8Array(w*h);for(let i=0;i<L.length;i++){let j=i*4;L[i]=nearest([data[j],data[j+1],data[j+2]],current.palette)}let passes=detail==='simple'?4:detail==='standard'?3:2;for(let p=0;p<passes;p++)L=modePass(L,w,h);let minArea=detail==='simple'?120:detail==='standard'?70:40,cs=components(L,w,h,minArea);lastLabels=L;lastComps=cs;cvs.segmented.width=cvs.mystery.width=w;cvs.segmented.height=cvs.mystery.height=h;let si=ctx.segmented.createImageData(w,h);for(let i=0;i<L.length;i++){let c=current.palette[L[i]],j=i*4;si.data[j]=c[0];si.data[j+1]=c[1];si.data[j+2]=c[2];si.data[j+3]=255}ctx.segmented.putImageData(si,0,0);ctx.mystery.fillStyle='#fff';ctx.mystery.fillRect(0,0,w,h);ctx.mystery.strokeStyle='#222';ctx.mystery.lineWidth=$('outline').value==='strong'?1.35:1;ctx.mystery.beginPath();for(let y=0;y<h;y++)for(let x=0;x<w;x++){let i=y*w+x,l=L[i];if(x<w-1&&L[i+1]!==l){ctx.mystery.moveTo(x+1,y);ctx.mystery.lineTo(x+1,y+1)}if(y<h-1&&L[i+w]!==l){ctx.mystery.moveTo(x,y+1);ctx.mystery.lineTo(x+1,y+1)}}ctx.mystery.stroke();ctx.mystery.textAlign='center';ctx.mystery.textBaseline='middle';for(const c of cs){if(c.size<minArea*1.4)continue;let p=safePoint(c,L,w,h),font=Math.max(7,Math.min(14,Math.floor(p.r*1.25)));if(p.r<5)continue;let txt=codeFor(c.lab);ctx.mystery.font=`700 ${font}px system-ui`;let tw=ctx.mystery.measureText(txt).width;if(tw>p.r*1.8)continue;ctx.mystery.fillStyle='rgba(255,255,255,.92)';ctx.mystery.fillRect(p.x-tw/2-1,p.y-font/2-1,tw+2,font+2);ctx.mystery.fillStyle='#222';ctx.mystery.fillText(txt,p.x,p.y)}current.segmented=cvs.segmented.toDataURL('image/png');current.mystery=cvs.mystery.toDataURL('image/png');current.lineApproved=false;current.finalApproved=false;current.status='line review';$('approveLine').disabled=false;$('lineStatus').innerHTML=`<small>${cs.length} cleaned colouring regions. Tiny texture islands have been merged rather than traced.</small>`;$('buildLine').disabled=false;save()};
$('approveLine').onclick=()=>{if(!current?.mystery)return;current.lineApproved=true;current.status='line approved';current.finalApproved=false;save();showStage('final');loadImage(current.mystery).then(m=>drawImageFit(m,cvs.final,ctx.final,700));renderFinalPalette();$('finalApprove').disabled=false};
function renderFinalPalette(){if(!current?.palette)return;$('finalPalette').innerHTML=current.palette.map((c,i)=>`<span class="sw"><span class="dot" style="background:${hex(c)}"></span><b>${codeFor(i)}</b></span>`).join('');$('finalApprove').disabled=!current.lineApproved}
$('finalApprove').onclick=()=>{if(!current?.lineApproved)return;current.finalApproved=true;current.status='complete';current.completedAt=Date.now();save();showStage('final');alert(`Design #${current.number} is complete: Colour Key + mystery page + colour palette.`)};
function completed(){return designs.filter(d=>d.finalApproved)}
function renderGallery(){let arr=completed(),host=$('galleryPages');host.innerHTML='';if(!arr.length){host.innerHTML='<section class="card empty">Completed coloured images will appear here.</section>';return}let mode=$('galleryMode').value,i=0;while(i<arr.length){let remain=arr.length-i,count=4,cls='layout4';if(mode==='2'){count=2;cls='layout2'}else if(mode==='3'){count=3;cls='layout3'}else if(mode==='auto'){let land=arr.slice(i,i+3).some(d=>d.aspect>1.12);if(land&&remain>=3){count=3;cls='layout3'}else{count=Math.min(4,remain);cls=count===2?'layout2':count===3?'layout3':'layout4'}}let page=document.createElement('section');page.className=`galleryPage ${cls}`;arr.slice(i,i+count).forEach(d=>{let x=document.createElement('div');x.className='galleryItem';x.innerHTML=`<img src="${d.artwork||d.original}"><span class="num">#${d.number}</span>`;page.appendChild(x)});host.appendChild(page);i+=count}}
$('galleryMode').onchange=renderGallery;
function renderStructure(){let a=completed(),g=$('galleryMode').value==='2'?Math.ceil(a.length/2):$('galleryMode').value==='3'?Math.ceil(a.length/3):Math.ceil(a.length/4);$('structure').innerHTML=`<p><strong>Opening:</strong> dedication page</p><p><strong>Completed design pairs:</strong> ${a.length} of 40</p><p><strong>Colouring section:</strong> ${a.length*2} pages (${a.length} Colour Keys + ${a.length} mystery pages)</p><p><strong>Completed Images:</strong> approximately ${g} gallery page${g===1?'':'s'}</p><p><strong>Current book:</strong> approximately ${1+a.length*2+g} A4 pages</p>`}
$('previewBook').onclick=renderStructure;$('printBook').onclick=()=>{renderStructure();window.print()};renderList();renderGallery();renderStructure();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=2').catch(()=>{});