/* v26 simple crop editor; swatch source is never modified */
(()=>{
 let active=null,working=null,rect={x:0,y:0,w:1,h:1};
 const cfg={main:{preview:'mainPreview',name:'Completed artwork'},line:{preview:'linePreview',name:'Colourless mystery'}};
 function ensure(){
  Object.entries(cfg).forEach(([t,c])=>{const im=document.getElementById(c.preview);if(!im||document.getElementById('v26-'+t))return;const d=document.createElement('div');d.id='v26-'+t;d.className='v26Btns';d.innerHTML='<button type="button" class="small">✂ Crop</button><button type="button" class="small">Restore original</button>';const old=document.getElementById(t+'RotateControls');(old||im.closest('.preview')).after(d);d.children[0].onclick=()=>open(t);d.children[1].onclick=()=>restore(t)});
  if(document.getElementById('v26Modal'))return;const m=document.createElement('div');m.id='v26Modal';m.className='v26Modal hidden';m.innerHTML='<div class="v26Box"><div class="v26Top"><strong id="v26Title">Crop</strong><button id="v26X">×</button></div><div class="v26Work"><img id="v26Img"><div id="v26Sel"><i data-h="tl"></i><i data-h="tr"></i><i data-h="bl"></i><i data-h="br"></i></div></div><div class="note">Move the purple box over the part you want to keep. Drag the white corner handles to resize it.</div><div class="v26Actions"><button id="v26Cancel">Cancel</button><button id="v26All">Select all</button><button id="v26Apply" class="primary">Apply crop</button></div></div>';document.body.appendChild(m);
  document.getElementById('v26X').onclick=close;document.getElementById('v26Cancel').onclick=close;document.getElementById('v26All').onclick=()=>{rect={x:0,y:0,w:1,h:1};draw()};document.getElementById('v26Apply').onclick=apply;wire();
 }
 async function open(t){if(!current||!current[t])return;active=t;if(!current[t+'Original'])current[t+'Original']=current[t];working=current[t];rect={x:.02,y:.02,w:.96,h:.96};const im=document.getElementById('v26Img');im.src=working;await new Promise(r=>{if(im.complete)r();else im.onload=r});document.getElementById('v26Title').textContent='Crop '+cfg[t].name;document.getElementById('v26Modal').classList.remove('hidden');draw()}
 function close(){document.getElementById('v26Modal').classList.add('hidden');active=null}
 function draw(){const s=document.getElementById('v26Sel');s.style.left=rect.x*100+'%';s.style.top=rect.y*100+'%';s.style.width=rect.w*100+'%';s.style.height=rect.h*100+'%'}
 function wire(){const s=document.getElementById('v26Sel');let d=null;s.onpointerdown=e=>{e.preventDefault();const h=e.target.dataset.h||'move';d={h,x:e.clientX,y:e.clientY,r:{...rect}};s.setPointerCapture(e.pointerId)};s.onpointermove=e=>{if(!d)return;const b=s.parentElement.getBoundingClientRect(),dx=(e.clientX-d.x)/b.width,dy=(e.clientY-d.y)/b.height,r=d.r,n={...r},min=.08;if(d.h==='move'){n.x=Math.max(0,Math.min(1-r.w,r.x+dx));n.y=Math.max(0,Math.min(1-r.h,r.y+dy))}else{if(d.h.includes('l')){n.x=Math.max(0,Math.min(r.x+r.w-min,r.x+dx));n.w=r.w+r.x-n.x}if(d.h.includes('r'))n.w=Math.max(min,Math.min(1-r.x,r.w+dx));if(d.h.includes('t')){n.y=Math.max(0,Math.min(r.y+r.h-min,r.y+dy));n.h=r.h+r.y-n.y}if(d.h.includes('b'))n.h=Math.max(min,Math.min(1-r.y,r.h+dy))}rect=n;draw()};s.onpointerup=s.onpointercancel=()=>d=null}
 async function apply(){if(!active)return;const im=await img(working),x=Math.round(rect.x*im.naturalWidth),y=Math.round(rect.y*im.naturalHeight),w=Math.max(1,Math.round(rect.w*im.naturalWidth)),h=Math.max(1,Math.round(rect.h*im.naturalHeight)),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,x,y,w,h,0,0,w,h);current[active]=c.toDataURL('image/jpeg',.96);current[active+'Rotation']=0;document.getElementById(cfg[active].preview).src=current[active];checkUploads();await save();close()}
 async function restore(t){if(!current?.[t+'Original'])return;current[t]=current[t+'Original'];delete current[t+'Original'];current[t+'Rotation']=0;document.getElementById(cfg[t].preview).src=current[t];checkUploads();await save()}
 const st=document.createElement('style');st.textContent='.v26Btns{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin:6px 0 10px}.v26Modal{position:fixed;inset:0;z-index:999;background:#000c;display:flex;align-items:center;justify-content:center;padding:10px}.v26Box{width:min(920px,96vw);max-height:96vh;overflow:auto;background:#fff;border-radius:15px;padding:12px}.v26Top{display:flex;justify-content:space-between;align-items:center}.v26Work{position:relative;width:fit-content;max-width:100%;margin:10px auto;line-height:0;touch-action:none}.v26Work img{display:block;max-width:100%;max-height:65vh;width:auto;height:auto}.v26Work #v26Sel{position:absolute;border:3px solid #6b4eff;box-shadow:0 0 0 9999px #0008;touch-action:none;cursor:move}.v26Work i{position:absolute;width:24px;height:24px;border-radius:50%;background:#fff;border:3px solid #6b4eff}.v26Work i[data-h=tl]{left:-13px;top:-13px}.v26Work i[data-h=tr]{right:-13px;top:-13px}.v26Work i[data-h=bl]{left:-13px;bottom:-13px}.v26Work i[data-h=br]{right:-13px;bottom:-13px}.v26Actions{display:grid;grid-template-columns:1fr 1fr 1fr;gap:7px;margin-top:8px}';document.head.appendChild(st);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensure);else ensure();
})();