// Mystery Book Studio — colourable structural line-art renderer v7
// Preserves the original artwork, but deliberately suppresses micro-texture before building colourable regions.
(function(){
 const btn=document.getElementById('buildLine'); if(!btn)return;
 const d2=(a,b)=>{let r=a[0]-b[0],g=a[1]-b[1],c=a[2]-b[2];return r*r+g*g+c*c};
 function nearest(rgb,p){let b=0,bd=1e20;for(let k=0;k<p.length;k++){let d=d2(rgb,p[k]);if(d<bd){bd=d;b=k}}return b}
 function comps(L,w,h){const seen=new Uint8Array(L.length),q=new Int32Array(L.length),out=[];for(let s=0;s<L.length;s++){if(seen[s])continue;let lab=L[s],hd=0,tl=0,sx=0,sy=0,minx=w,maxx=0,miny=h,maxy=0,pts=[];q[tl++]=s;seen[s]=1;while(hd<tl){let i=q[hd++],x=i%w,y=(i/w)|0;pts.push(i);sx+=x;sy+=y;minx=Math.min(minx,x);maxx=Math.max(maxx,x);miny=Math.min(miny,y);maxy=Math.max(maxy,y);for(const n of [x?i-1:-1,x<w-1?i+1:-1,y?i-w:-1,y<h-1?i+w:-1])if(n>=0&&!seen[n]&&L[n]===lab){seen[n]=1;q[tl++]=n}}out.push({lab,pts,size:pts.length,cx:sx/pts.length,cy:sy/pts.length,minx,maxx,miny,maxy})}return out}
 function majority(L,w,h,r=1){let O=new Uint8Array(L.length),cnt=new Uint16Array(32);for(let y=0;y<h;y++)for(let x=0;x<w;x++){cnt.fill(0);for(let yy=Math.max(0,y-r);yy<=Math.min(h-1,y+r);yy++)for(let xx=Math.max(0,x-r);xx<=Math.min(w-1,x+r);xx++)cnt[L[yy*w+xx]]++;let b=L[y*w+x],n=cnt[b];for(let k=0;k<cnt.length;k++)if(cnt[k]>n){b=k;n=cnt[k]}O[y*w+x]=b}return O}
 function mergeSmall(L,w,h,p,minArea){let cs=comps(L,w,h).sort((a,b)=>a.size-b.size);for(const c of cs){if(c.size>=minArea)break;let adj=new Map;for(const i of c.pts){let x=i%w,y=(i/w)|0;for(const n of [x?i-1:-1,x<w-1?i+1:-1,y?i-w:-1,y<h-1?i+w:-1])if(n>=0&&L[n]!==c.lab)adj.set(L[n],(adj.get(L[n])||0)+1)}let best=c.lab,score=-1e20;for(const [lab,b] of adj){let s=b-Math.sqrt(d2(p[c.lab],p[lab]))*.035;if(s>score){score=s;best=lab}}if(best!==c.lab)for(const i of c.pts)L[i]=best}}
 function clean(L,w,h,p,detail){
   // Physical colourability matters more than raw edge count. Work at modest resolution and remove texture islands repeatedly.
   const cfg=detail==='simple'?{passes:3,r:2,areas:[18,30,48,72,105,150],max:420}:detail==='standard'?{passes:2,r:2,areas:[12,20,32,48,70,100,140],max:650}:{passes:2,r:1,areas:[8,14,22,34,50,72,100],max:900};
   for(let z=0;z<cfg.passes;z++)L=majority(L,w,h,cfg.r);
   for(const a of cfg.areas){mergeSmall(L,w,h,p,a);L=majority(L,w,h,1);if(comps(L,w,h).length<=cfg.max)break}
   let a=cfg.areas[cfg.areas.length-1],cs=comps(L,w,h);while(cs.length>cfg.max&&a<300){a=Math.round(a*1.3);mergeSmall(L,w,h,p,a);L=majority(L,w,h,1);cs=comps(L,w,h)}return{L,cs};
 }
 function labelPoint(c,L,w,h){let best={x:Math.round(c.cx),y:Math.round(c.cy),r:0},step=Math.max(1,Math.floor(Math.min(c.maxx-c.minx,c.maxy-c.miny)/10));for(let y=c.miny;y<=c.maxy;y+=step)for(let x=c.minx;x<=c.maxx;x+=step){if(L[y*w+x]!==c.lab)continue;let r=1;outer:for(;r<18;r++){if(x-r<0||x+r>=w||y-r<0||y+r>=h)break;for(let xx=x-r;xx<=x+r;xx++)if(L[(y-r)*w+xx]!==c.lab||L[(y+r)*w+xx]!==c.lab)break outer;for(let yy=y-r;yy<=y+r;yy++)if(L[yy*w+x-r]!==c.lab||L[yy*w+x+r]!==c.lab)break outer}if(r>best.r)best={x,y,r}}return best}
 function render(L,w,h,cs,detail,strong,outW,outH){let o=document.createElement('canvas');o.width=outW;o.height=outH;let c=o.getContext('2d'),sx=outW/w,sy=outH/h;c.fillStyle='#fff';c.fillRect(0,0,outW,outH);c.strokeStyle='#202020';c.lineWidth=strong?1.5:1.1;c.lineCap='round';c.lineJoin='round';c.beginPath();for(let y=0;y<h-1;y++)for(let x=0;x<w-1;x++){let i=y*w+x,l=L[i];if(L[i+1]!==l){let xx=(x+1)*sx;c.moveTo(xx,y*sy);c.lineTo(xx,(y+1)*sy)}if(L[i+w]!==l){let yy=(y+1)*sy;c.moveTo(x*sx,yy);c.lineTo((x+1)*sx,yy)}}c.stroke();c.textAlign='center';c.textBaseline='middle';let min=detail==='simple'?32:detail==='standard'?24:18;for(const z of cs){if(z.size<min)continue;let p=labelPoint(z,L,w,h);if(p.r<4)continue;let code=typeof codeFor==='function'?codeFor(z.lab):String(z.lab+1),fs=Math.max(7,Math.min(13,Math.floor(p.r*sx*.9)));c.font=`700 ${fs}px system-ui`;let tw=c.measureText(code).width;if(tw>p.r*sx*1.8)continue;let px=p.x*sx,py=p.y*sy;c.fillStyle='rgba(255,255,255,.96)';c.fillRect(px-tw/2-2,py-fs/2-1,tw+4,fs+2);c.fillStyle='#222';c.fillText(code,px,py)}return o}
 function original(im){let w=Math.min(1000,im.naturalWidth),h=Math.round(w*im.naturalHeight/im.naturalWidth);cvs.segmented.width=w;cvs.segmented.height=h;ctx.segmented.clearRect(0,0,w,h);ctx.segmented.imageSmoothingEnabled=true;ctx.segmented.imageSmoothingQuality='high';ctx.segmented.drawImage(im,0,0,w,h)}
 btn.onclick=async()=>{if(!current?.keyApproved||!current.palette)return alert('Approve the Colour Key first.');btn.disabled=true;let st=document.getElementById('lineStatus');st.innerHTML='<small>Removing tiny decorative texture and building colourable structural regions…</small>';try{artImg=await loadImage(current.artwork);let detail=document.getElementById('detail').value;original(artImg);
   // Detailed no longer means trace every pixel: it means more colourable sections while still suppressing flowers, moss and speckle texture.
   let tw=detail==='simple'?260:detail==='standard'?310:360,scale=Math.min(1,tw/artImg.naturalWidth),w=Math.max(100,Math.round(artImg.naturalWidth*scale)),h=Math.max(100,Math.round(artImg.naturalHeight*scale));let work=document.createElement('canvas');work.width=w;work.height=h;let wc=work.getContext('2d',{willReadFrequently:true});wc.imageSmoothingEnabled=true;wc.imageSmoothingQuality='high';wc.filter=detail==='simple'?'blur(2.4px)':detail==='standard'?'blur(1.7px)':'blur(1.15px)';wc.drawImage(artImg,0,0,w,h);let data=wc.getImageData(0,0,w,h).data,L=new Uint8Array(w*h);for(let i=0;i<L.length;i++){let j=i*4;L[i]=nearest([data[j],data[j+1],data[j+2]],current.palette)}let z=clean(L,w,h,current.palette,detail);L=z.L;let cs=comps(L,w,h),outW=Math.min(1000,artImg.naturalWidth),outH=Math.round(outW*artImg.naturalHeight/artImg.naturalWidth),line=render(L,w,h,cs,detail,document.getElementById('outline').value==='strong',outW,outH);cvs.mystery.width=outW;cvs.mystery.height=outH;ctx.mystery.clearRect(0,0,outW,outH);ctx.mystery.drawImage(line,0,0);current.segmented=current.artwork;current.mystery=cvs.mystery.toDataURL('image/png');current.lineApproved=false;current.finalApproved=false;current.status='key approved';if(typeof save==='function')save();document.getElementById('approveLine').disabled=false;st.innerHTML=`<small><strong>${cs.length} colourable regions.</strong> Tiny flowers, moss, speckles and repeated texture are deliberately consolidated. The original artwork remains untouched.</small>`}catch(e){console.error(e);st.innerHTML='<small>Line generation failed. Please try again.</small>'}finally{btn.disabled=false}}
})();